language: c

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs nunit-console > /dev/null
  - mozroots --import --sync
  - mv -f .nuget/NuGet.mono.targets .nuget/NuGet.targets
  - export EnableNuGetPackageRestore=true
  
script:
  - xbuild HelloWorld.sln
  - nunit-console HelloWorld.Tests/bin/Debug/HelloWorld.Tests.dll
  
deploy:
  provider: heroku
  buildpack: https://github.com/friism/heroku-buildpack-mono.git
  api_key: "[app-key]"
  app: [app-name]